[package]
name = "nes-emulator-methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "0.19.1" }
nes-rust-core = {path = "../core" }

[package.metadata.risc0]
methods = ["guest"]